### ISSUE TITLE
Pointer comparisions are undefined in C

### ISSUE THREAD

**Issue by danielsn** [pornin/CTTK#1]
https://github.com/pornin/CTTK/blob/master/src/copy.c#L61

https://wiki.sei.cmu.edu/confluence/display/c/ARR36-C.+Do+not+subtract+or+compare+two+pointers+that+do+not+refer+to+the+same+array

**Comment by pornin** [comment]
The code does not compare pointers, but the values with the integer type `uintptr_t`, and one is certainly allowed to compare integers.

IF the two source pointers designate overlapping memory areas, then they are part of the same underlying object (in the C standard sense), and the comparison of the `uintptr_t` values will yield the proper response. If the the two source pointers designate distinct objects, then indeed there are no semantics attached to the obtained apparent order, but that is not a problem, since in that case both loop versions will produce identical results.

(I admit that the fact that pointer values cast to `uintptr_t` preserve order when the pointers come from the same storage object is _not_ guaranteed by the standard. However, it will work on all existing systems, and since it does not trigger any "undefined behavior" in the sense of the standard, it won't imply compiler shenanigans.)
